/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Modelos.ModeloProducto;
import Modelos.ModeloVenta;
import Negocio.NegocioProducto;
import Negocio.NegocioVenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joshua
 */
public class ProductoFmr extends javax.swing.JFrame {

    String accion = "Venta Productos";
    NegocioVenta nv = new NegocioVenta();
    NegocioProducto np = new NegocioProducto();

    /**
     * Creates new form ProductoFmr
     */
    public ProductoFmr(String accion) {
        this.accion = accion;
        initComponents();
        this.setLocationRelativeTo(null);
        if (accion == "Venta Productos") {
            this.setTitle("Venta de Productos");
            LabelTitulo.setText("Venta de Productos");
            LabelProducto.setText("Producto a Vender");
            labelCampoTexto.setText("Precio :");
            botonRealizarAccion.setText("Vender");
            cantidadOPreciotxt.setEditable(false);
            crearEventoCombo();
            llenarComboVenta();
        } else if (accion == "Inventariar Productos") {
            this.setTitle("Inventariar Productos");
            LabelTitulo.setText("Inventariar Productos");
            LabelProducto.setText("Producto a Inventariar");
            cantidadOPreciotxt.setText("");
            botonRealizarAccion.setText("Inventariar");
            llenarComboInv();
        }

        
    }

    public ProductoFmr() {
        initComponents();
        this.setTitle("Venta Productos");
        this.setLocationRelativeTo(null);
    }

    private void crearEventoCombo() {
        comboProducto.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ponerPrecio();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelProducto = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        labelCampoTexto = new javax.swing.JLabel();
        cantidadOPreciotxt = new javax.swing.JTextField();
        botonRealizarAccion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonRealizarAccion.setText("Vender");
        botonRealizarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarAccionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(botonRealizarAccion)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(LabelProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCampoTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cantidadOPreciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboProducto)
                    .addComponent(LabelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadOPreciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRealizarAccion)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarAccionActionPerformed
        if (accion.equals("Venta Productos")) {
            List productos = np.desplegarProductos();
            ModeloVenta venta;
            String nombre = comboProducto.getItemAt(comboProducto.getSelectedIndex());
            for (int i = 0; i < productos.size(); i++) {
                ModeloProducto prod = (ModeloProducto) productos.get(i);
                if (prod.getNombre().equals(nombre)) {
                    venta = new ModeloVenta();
                    venta.setProducto(prod);
                    venta.setFechaventa(LocalDate.now());
                    if (realizarVenta(venta)) {
                        JOptionPane.showMessageDialog(null, "Se registró la venta \n El precio es de: " + prod.getPrecio());
                    } else {
                        JOptionPane.showMessageDialog(new JPanel(), "No se pudo registrar la venta: Revise la consola", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }
            }

        }
    }//GEN-LAST:event_botonRealizarAccionActionPerformed

    private boolean realizarVenta(ModeloVenta venta) {

        //boolean seVendio = np.addProducto(venta.getProducto());
        return nv.addVenta(venta);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoFmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoFmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoFmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoFmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoFmr().setVisible(true);
            }
        });
    }

    private void llenarComboVenta() {
        List productos = np.desplegarProductos();
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        for (int i = 0; i < productos.size(); i++) {
            ModeloProducto prod = (ModeloProducto) productos.get(i);
            if (prod.getCantidad() != 0) {
                dml.addElement(prod.getNombre());
            }
        }
        comboProducto.setModel(dml);
        ponerPrecio();
    }

    private void llenarComboInv() {
        List productos = np.desplegarProductos();
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        for (int i = 0; i < productos.size(); i++) {
            ModeloProducto prod = (ModeloProducto) productos.get(i);
            dml.addElement(prod.getNombre());
        }
        comboProducto.setModel(dml);
    }

    private void ponerPrecio() {
        String nombre = comboProducto.getItemAt(comboProducto.getSelectedIndex());
        List productos = np.desplegarProductos();

        for (int i = 0; i < productos.size(); i++) {
            ModeloProducto prod = (ModeloProducto) productos.get(i);
            if (prod.getNombre().equals(nombre)) {
                cantidadOPreciotxt.setText("" + prod.getPrecio());
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelProducto;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JButton botonRealizarAccion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField cantidadOPreciotxt;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel labelCampoTexto;
    // End of variables declaration//GEN-END:variables
}
